### ISSUE TITLE
Bug: show scroll in guides code blocks

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#449]
![selection_118](https://user-images.githubusercontent.com/2227572/40384218-412c6730-5e03-11e8-8655-94b89241c36e.png)

This is because of:

```css
.u-horizontal-scroll {
  overflow-x: scroll
}
```

This could be solved with this change:

```css
.u-horizontal-scroll {
  overflow-x: auto
}
```

@csubira
